### ISSUE TITLE
Customer Feedback Proposal 

### ISSUE THREAD

**Issue by elliottdebruin** [DavidThien/IDE-IT#1]
As a customer, the proposal answers most of the questions I could have. The problem to be solved is clear as are the inadequacies of current solutions. It is also clear that this team will evaluate their approach through unit and suite testing, as well as experiments. Perhaps a valuable test group for experimentation could be programmers who have never used Eclipse before. This team has a schedule, although some of the points on it may be difficult to measure (though not impossible). An example is "Identify the extension points we need to integrate the plugin". This team also included ample citations to multiple sources.
    We also, however, see a few points in your proposal that need to be addressed and strengthened. The first paragraph of your proposal is very drawn out and does not tell the customer what your tool is. I think that you should have one or two examples of why you want to create IDE-IT, but then get straight to the point of what IDE-IT is and what it will do for the customer. This will draw the customer in more instead of needing to read half a page before they know what the proposal is for. Another point that we thought was important to address is that you do not give many concrete examples of how IDE-IT will work. You describe that the tool will track user input and display a tip once a specific sequence of input is registered, but I think this is vague to someone looking to use your plugin. It would be helpful to give an example of a sequence of user input that would trigger a specific feature to be discovered. I think it is also important to specify how much input data you will need from the user before a tip will be displayed. Will they get a tip the first time they do not use a feature or the third or fourth time? Lastly, you mention in the opening paragraph that some IDE tools are not used because they are non trivial to learn. You should be clear about what your tips will say when they are displayed, because if you present a tip for a non trivial feature but do not explain how to use it I think the user will be just as likely to skip over it as will other tip suggestion tools.

**Comment by cagesellchen** [comment]
**IDE-IT Frontend Project Proposal Review**
**Summary: 7/7 pts**

**Comments** : This looks like an ambitious project, but we think it will be really useful and well worth the effort! Overall this proposal was really solid and generally fulfilled all of the requirements. A few suggestions for improving it (many of them nitpicky) were…

•	One of the requirements was to explain what’s new in your approach and why you think it will be successful. The first part you did really well, but we think you could explain a bit more about why it will be successful. For example, are current feature suggestion tools popular amongst Eclipse users (do you have a large customer base already)? 
•	You start off by discussing how IDEs have amazing tools that are never used, and then list a bunch of different reasons why users don't utilize all the features of an IDE. We felt like it was long and didn’t flow well; it seemed like you just copied a bunch of evidence down without analyzing/commenting on it. It might be better to pick 2-3 examples and explain why each one matters.
•	You make a great point about how current tips can be "more of an annoyance than a help", and we think that's something you should address more directly. With similar tools, like clippy, people get annoyed by them really easily. Reinforcing this with more commentary would strengthen your argument.
•	You talk about trying to make it relevant and non-invasive, but it would be good to have something in your evaluation/testing about assessing how people respond to the tips/if they are annoying or not, because that would be one of the major barriers to getting people to actually use it.
•	How will you address new versions of Eclipse changing shortcuts/features (if at all)?
•	Many of Eclipse’s features don’t directly correlate to a clear action by the user. Are there enough to justify the project? Your proposal would be stronger if you gave more examples of what actions/features you plan to track
•	This is potentially a really large project, and you may want to think about picking a handful of specific features for “v1” and listing them in your proposal. The examples would strengthen the proposal, and it could help keep the project in-scope for the class.

**Rubric**

 **I understand the problem this group is trying to solve**. 
Yes – Eclipse users often don’t utilize the full product because they don’t know about features/tools, and thus are less productive. 

**I understand why current solutions are insufficient.**
 Yes – plugins will randomly suggest tools, or remind of shortcuts to access a feature that is being manually accessed, but none of them analyze users’ habits to suggest/discover relevant tools.

**I understand this group's proposed approach.**
 Yes - a plugin that analyzes users’ keystrokes to suggest relevant features/tools. The project will be split into a frontend and backend team.

**I understand how this team will evaluate their approach.**
 Yes – experimentation testing: having people use the plugin to see if it suggests useful tools, and directing users to perform certain actions to make sure their keystrokes are recognized by the plugin.

**This team included a schedule.**
 Yes

**Every item on this team's schedule is measurable.**
 Yes

**This team included appropriate citations to related work, including from the scientific literature.**
 Yes

**Comment by johnbarUW** [comment]
Updated the project report based on customer feedback as follows.
- Removed some of the motivation and split it into "Motivation" and "Related work"
- Gave more concrete examples of what features we would support
- Did not go into specifics on what user actions would trigger a feature suggestion. This seems like internal information that is not needed for a customer. They should be able to trust that this plugin will catch their actions and provide suggestions, not provide one of the exact sequences they need to do in order to see a suggestion.
- Much of the comments about suggestions being annoying and irrelevant to users is completely valid. One nice thing about focusing purely on the backend service is to allow the frontend to do the filtering and interaction with the user to provide suggestions in a non-annoying manner. And allow users to turn off certain suggestions if they don't find them helpful.
